### ISSUE TITLE
ms-exchange-versions-dict.json: 5.0.1497 instead of 15.0.1497

### ISSUE THREAD

**Issue by thkn-hofa** [righel/ms-exchange-version-nse#1]
Hi,

The first entry in "ms-exchange-versions-dict.json" is 5.0.1497 but should be 15.0.1497 (build should be 15.0.1497.44). Maybe an issue on the source from where you parse the lists but I don't know python enough to go troubleshooting myself.

Best regards,
Thomas

**Comment by righel** [comment]
Nice catch, indeed seems there's a typo in one of the sources I'm pulling the build numbers from, added a quick fix and notified the website.

fixed via 3adbf3c763af937eecb37103a840120524a1a851

sorry for the delay, and thanks.

**Comment by thkn-hofa** [comment]
No, thank **you** for your work. Also: there are no deadlines for free work on free-to-use software so I will not be accepting your apology 😅 Thanks again!
